

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
        <head>
        </head>
      {/* <link rel="stylesheet" href="htt  ps://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"></link> */}
      <body>{children}</body>
    </html>
  )
}
